from Tryaccept.py import *

raise ValueError("Testing)
